language: bash

before_script:
    - curl -L "https://github.com/kward/shunit2/archive/v2.1.7.tar.gz" | tar zx

script:
    - bash tests/simple_tests/equality_test.sh
    - bash tests/simple_tests/square_test.sh
